[package]
name = "noted2xero_cli"
version = "0.4.0"
authors = ["Philip Rodrigues <phiroict@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
noted2xero_core = {path = "../noted2xero_core", version ="0.4.0-rc3"}
log = "0.4.14"
simple_logger = "1.16.0"
env_logger = "0.9.0"
csv = "1.1.6"
glob = "0.3.0"
chrono = "0.4.19"

